services:
  processar:
    build: .
    container_name: processar-sqs
    environment:
      AWS_DEFAULT_REGION: us-east-1
      QUEUE_URL: https://sqs.us-east-1.amazonaws.com/794038217446/formacao-mensageria
    # Monta as credenciais do profile awscli para uso local
    volumes:
      - ~/.aws:/root/.aws:ro
    # Para modo contínuo, o container fica rodando
    restart: unless-stopped
